import Head from 'next/head'
import MiddleBar from '../components/MiddleBar';
import SideBarPage from '../components/SideBarPage';
import TopBoxes from '../components/TopBoxes';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Agent-Clients</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SideBarPage />
        <TopBoxes />
        <MiddleBar />
      </main>
    </div>
  );
}
